// <auto-generated />
using System;
using GoodHamburger.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoodHamburger.Infrastructure.Migrations
{
    [DbContext(typeof(GoodHamburgerContext))]
    [Migration("20260426031002_RefatoracaoOwnsMany")]
    partial class RefatoracaoOwnsMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFinal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Sanduiche",
                            Nome = "X Burger",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Sanduiche",
                            Nome = "X Egg",
                            Preco = 4.50m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Sanduiche",
                            Nome = "X Bacon",
                            Preco = 7.00m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Acompanhamento",
                            Nome = "Batata Frita",
                            Preco = 2.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Bebida",
                            Nome = "Refrigerante",
                            Preco = 2.50m
                        });
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Pedido", b =>
                {
                    b.OwnsMany("GoodHamburger.Domain.Entities.ItemPedido", "Itens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Categoria")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<int>("ProdutoId")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("PedidoId");

                            b1.HasIndex("ProdutoId");

                            b1.ToTable("ItensPedido", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.HasOne("GoodHamburger.Domain.Entities.Produto", "Produto")
                                .WithMany()
                                .HasForeignKey("ProdutoId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Produto");
                        });

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
